### ISSUE TITLE
Control+Alt+P no longer work in mac (atom 0.175.0)

### ISSUE THREAD

**Issue by ericfong** [chuckhendo/project-quick-open#13]
Suddenly doesn't work.

**Comment by jsg2021** [comment]
my pull request will fix that.

**Comment by chuckhendo** [comment]
@jsg2021 pull request does seem to have fixed it. I've published 0.3.2 of the plugin - can you take a look and see if it works now?

**Comment by jsg2021** [comment]
It does for me :)

**Comment by ericfong** [comment]
Thanks, you save my life!
