### ISSUE TITLE
With Atom's Built-in themes (esp One Dark/Light) the menu looks weird. 

### ISSUE THREAD

**Issue by jsg2021** [chuckhendo/project-quick-open#16]
There is no cursor, no text shows up as you type. Options look unstyled.

This is with "o" typed...
![screen shot 2015-03-05 at 11 38 05 am](https://cloud.githubusercontent.com/assets/577453/6510515/3524003a-c32c-11e4-8633-ec7fa0e3f1ee.png)

Compare with the fuzzy finder:
![screen shot 2015-03-05 at 11 25 43 am](https://cloud.githubusercontent.com/assets/577453/6510550/69f64fa2-c32c-11e4-970f-8b721b08f34d.png)

and the command pallet:
![screen shot 2015-03-05 at 11 39 52 am](https://cloud.githubusercontent.com/assets/577453/6510557/721bb74e-c32c-11e4-9040-b648c864170f.png)

**Comment by chuckhendo** [comment]
I just published a new version (0.4.0) that uses newer Atom APIs. That should resolve the issue

**Comment by jsg2021** [comment]
much better :) thanks!
