### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [chuckhendo/project-quick-open#22]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.4.4`) of this package:

1. Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `<pack-name>` package
1. Use ::setPaths instead

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by chuckhendo** [comment]
Thank you! Changes implemented in cadb7f7e9b8ecff3fd3f441432f28f257ad180a1
