### ISSUE TITLE
Feature Request: Add New Project Folder

### ISSUE THREAD

**Issue by jacobmischka** [chuckhendo/project-quick-open#25]
It would be nice to be able to use this to add multiple project folders, instead of only being able to replace the one you currently have open.
![Like this](https://cloud.githubusercontent.com/assets/3939997/9941224/80057d02-5d39-11e5-92d1-d56d26c39211.png)

**Comment by chuckhendo** [comment]
@jacobmischka is this something you would still be interested in? I've haven't had time to dedicate to this project up until recently, and I could potentially see this being useful

**Comment by jacobmischka** [comment]
Not really, I've started opening atom with the command line using the path of the project I want to open. It would be useful though I think.
