### ISSUE TITLE
Issue when opening projects in fullscreen

### ISSUE THREAD

**Issue by themccallister** [chuckhendo/project-quick-open#4]
I am using the latest version of Atom, Mac and on a Macbook Pro Retina.

When I have a project open in fullscreen, and use the shortcut keys to open a new project the following happens. A blank gray bar shows over Atom. Its the same size as the top bar in Mac and the only way to fix it is to exit fullscreen, and enter fullscreen again.

That being said, this may be an Atom or Mac issue.

![screen shot 2014-06-10 at 4 45 52 pm](https://cloud.githubusercontent.com/assets/5354908/3238548/6509945a-f0f9-11e3-8bd1-6e70d8e6ac96.png)

**Comment by chuckhendo** [comment]
I've been unable to recreate this, and haven't heard anything else about the issue. Regardless, I think that it may be an issue with Atom or the Mac, but if you are able to find a set of steps to reproduce, please let me know and I can look into it.
